name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v1

      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm pack
        run: npm pack
      - uses: actions/upload-artifact@v2
        name: Upload Artifact
        with:
          name: angular-material-dynamic-themes.zip
          path: ./*.tgz